Parameters:
  Vpc:
    Type: AWS::EC2::VPC::Id
    Description: Select VPC for EC2 instance creation
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select the subnets for EC2 instance creation
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Select the security groups for EC2 instance creation
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Select EC2 instance type
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select key pair for EC2 instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
    InstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        InstanceProfileName: my-instance-profile
        Roles:
          - !Ref EC2SSMRole
      ImageId: ami-0c94855ba95c71c99 # Replace with appropriate AMI ID
      NetworkInterfaces:
        - GroupSet: !Ref SecurityGroups
          AssociatePublicIpAddress: false
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: !Select [0, !Ref Subnets]
          PrivateIpAddress: 10.0.0.10 # Replace with an appropriate IP address for your VPC
          Description: "Primary network interface"

  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.us-east-1.ssm
      VpcId: !Ref Vpc
      PrivateDnsEnabled: true
      SecurityGroupIds: !Ref SecurityGroups
      SubnetIds: !Ref Subnets

  SSMMessageEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.us-east-1.ssmmessages
      VpcId: !Ref Vpc
      PrivateDnsEnabled: true
      SecurityGroupIds: !Ref SecurityGroups
      SubnetIds: !Ref Subnets

  FlowLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Allow-Flow-Logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:log-group:/aws/vpc/flow-logs/*

  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt FlowLogRole.Arn
      LogGroupName: /aws/vpc/flow-logs
      ResourceId: !Ref Vpc
      ResourceType: VPC
      TrafficType: ALL

  EC2SSMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'ec2-ssm-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

Outputs:
  InstancePrivateIP:
    Value: !GetAtt EC2Instance.PrivateIp
  SSMEndpointId:
    Value: !Ref SSMEndpoint
  SSMMessageEndpointId:
    Value: !Ref SSMMessageEndpoint


