AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RandomNumber:
    Type: "Number"
    Description: "A random number used to generate unique bucket names"
Resources:
    Week06Bucket00:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: !Sub "week-06-star-wars-bucket-${RandomNumber}"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    Week06Bucket01:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: !Sub "week-06-bucket-${RandomNumber}"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false